### ISSUE TITLE
Can't build with GHC 8.2.1

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/dependent-db#1] opened 2017-07-23 19:23 UTC
I tried building `dependent-db` with GHC 8.2.1 recently. I had to apply these trivial patches to `Basics` to adapt to 8.2-specific changes:

```diff
diff --git a/Basics.hs b/Basics.hs
index 2b03e91..5172aa7 100644
--- a/Basics.hs
+++ b/Basics.hs
@@ -3,7 +3,7 @@
    This module defines all the plumbing needed to power the dependent database.
 -}
 
-{-# LANGUAGE TypeOperators, TypeFamilies, TypeApplications,
+{-# LANGUAGE CPP, TypeOperators, TypeFamilies, TypeApplications,
              ExplicitForAll, ScopedTypeVariables, GADTs, TypeFamilyDependencies,
              TypeInType, ConstraintKinds, UndecidableInstances,
              FlexibleInstances, MultiParamTypeClasses, FunctionalDependencies,
@@ -13,7 +13,7 @@
 module Basics where
 
 import Data.Type.Bool
-import Data.Type.Equality
+import Data.Type.Equality ((:~:)(..), TestEquality(..), type (==))
 import GHC.TypeLits
 import Data.Proxy
 import GHC.Exts
@@ -73,6 +73,12 @@ Nil %:++ x = x
 -- Type-indexed type representations
 -- Based on "A reflection on types"
 
+#if __GLASGOW_HASKELL__ >= 802
+type LiftedRep = 'LiftedRep
+#else
+type LiftedRep = 'PtrRepLifted
+#endif
+
 data TyCon (a :: k) where
   Int :: TyCon Int
   Bool :: TyCon Bool
@@ -82,7 +88,7 @@ data TyCon (a :: k) where
   Arrow :: TyCon (->)
   TYPE  :: TyCon TYPE
   RuntimeRep :: TyCon RuntimeRep
-  PtrRepLifted' :: TyCon 'PtrRepLifted
+  PtrRepLifted' :: TyCon LiftedRep
   -- If extending, add to eqTyCon too
 
 eqTyCon :: TyCon a -> TyCon b -> Maybe (a :~~: b)
@@ -211,7 +217,7 @@ instance TyConAble []        where tyCon = List
 instance TyConAble Maybe     where tyCon = Maybe
 instance TyConAble (->)      where tyCon = Arrow
 instance TyConAble TYPE      where tyCon = TYPE
-instance TyConAble 'PtrRepLifted   where tyCon = PtrRepLifted'
+instance TyConAble LiftedRep where tyCon = PtrRepLifted'
 instance TyConAble RuntimeRep    where tyCon = RuntimeRep
 
 -- Can't just define Typeable the way we want, because the instances
```

But after this, I hit a larger roadblock:

```
$ /opt/ghc/8.2.1/bin/ghci Main.hs
GHCi, version 8.2.1: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /home/rgscott/.ghci
[1 of 6] Compiling Basics           ( Basics.hs, interpreted )
[2 of 6] Compiling Instances        ( Instances.hs, interpreted )
[3 of 6] Compiling DB2              ( DB2.hs, interpreted )
[4 of 6] Compiling ReadDB           ( ReadDB.hs, interpreted )
[5 of 6] Compiling TH               ( TH.hs, interpreted )
[6 of 6] Compiling Main             ( Main.hs, interpreted )

Main.hs:20:10: error:
    • Could not deduce: Disjoint s s1 ~ 'True
      from the context: ReadSchema s1
        bound by a type expected by the context:
                   ReadSchema s1 => IO ()
        at Main.hs:20:10-58
      or from: ReadSchema s
        bound by a type expected by the context:
                   ReadSchema s => IO ()
        at Main.hs:20:10-58
    • In the second argument of ‘checkReadSchema’, namely
        ‘((readDB classes_sch) students_sch)’
      In the second argument of ‘checkReadSchema’, namely
        ‘((checkReadSchema classes_sch)
            ((readDB classes_sch) students_sch))’
      In the fourth argument of ‘checkInProxy’, namely
        ‘((checkReadSchema students_sch)
            ((checkReadSchema classes_sch)
               ((readDB classes_sch) students_sch)))’
    • Relevant bindings include
        students_sch :: Schema s1 (bound at Main.hs:19:40)
        classes_sch :: Schema s (bound at Main.hs:18:40)
   |
20 |        $(checkSchema 'readDB ['classes_sch, 'students_sch])
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Do you know what might be happening here?

**Comment by goldfirere** [comment] 2017-07-24 13:24
This was caused by an update to TH, where `'True` is now rendered as `PromotedT 'True` instead of `ConT 'True`. Anyway, fixed now.

**Closed as completed by goldfirere** 2017-07-24 13:24 UTC

**Comment by RyanGlScott** [comment] 2019-01-22 20:28
This issue has resurfaced once again on GHC 8.7:

```
[6 of 6] Compiling Main             ( ../triptych/dependent-db/Main.hs, interpreted )
Discarding: AppT (AppT (ConT GHC.Types.~) (AppT (AppT (ConT DB2.Disjoint) (VarT s_6989586621679192809)) (VarT s'_6989586621679192810))) (PromotedT GHC.Types.True)
head: ConT GHC.Types.~
args: [AppT (AppT (ConT DB2.Disjoint) (VarT s_6989586621679192809)) (VarT s'_6989586621679192810),PromotedT GHC.Types.True]

../triptych/dependent-db/Main.hs:20:10: error:
    • Could not deduce: Disjoint s s1 ~ 'True
        arising from a use of ‘readDB’
      from the context: ReadSchema s
        bound by a type expected by the context:
                   ReadSchema s => IO ()
        at ../triptych/dependent-db/Main.hs:20:10-58
      or from: ReadSchema s1
        bound by a type expected by the context:
                   ReadSchema s1 => IO ()
        at ../triptych/dependent-db/Main.hs:20:10-58
    • In the fourth argument of ‘checkInProxy’, namely
        ‘((readDB classes_sch) students_sch)’
      In the fourth argument of ‘checkInProxy’, namely
        ‘((((checkInProxy
               (Data.Proxy.Proxy :: Data.Proxy.Proxy "students"))
              (Data.Proxy.Proxy :: Data.Proxy.Proxy [Int]))
             (classes_sch %:++ students_sch))
            ((readDB classes_sch) students_sch))’
      In the fourth argument of ‘checkInProxy’, namely
        ‘((((checkInProxy (Data.Proxy.Proxy :: Data.Proxy.Proxy "prof"))
              (Data.Proxy.Proxy :: Data.Proxy.Proxy String))
             classes_sch)
            ((((checkInProxy (Data.Proxy.Proxy :: Data.Proxy.Proxy "students"))
                 (Data.Proxy.Proxy :: Data.Proxy.Proxy [Int]))
                (classes_sch %:++ students_sch))
               ((readDB classes_sch) students_sch)))’
    • Relevant bindings include
        students_sch :: Schema s1
          (bound at ../triptych/dependent-db/Main.hs:19:40)
        classes_sch :: Schema s
          (bound at ../triptych/dependent-db/Main.hs:18:40)
   |
20 |        $(checkSchema 'readDB ['classes_sch, 'students_sch])
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

It looks like GHC is now reifying the type of `readDB` with `ConT ''(~)` instead of `EqualityT` for some reason.

**Comment by goldfirere** [comment] 2019-01-25 01:28
Out of curiosity, how is it that you came across this? I was considering responding announcing this repo as abandon-ware, but clearly you were interested enough to compile this code.

**Comment by RyanGlScott** [comment] 2019-01-25 01:32
I build a hand-picked selection of Haskell repos before each major GHC release to test for regressions. `dependent-db` has caught a couple of bugs before, so it's definitely valuable in that regard :)

**Comment by goldfirere** [comment] 2019-01-25 01:53
Ah, but it's in the testsuite as `dependent/should_compile/RaeJobTalk`.

**Comment by RyanGlScott** [comment] 2019-01-25 02:39
Unfortunately, `RaeJobTalk` doesn't have the Template Haskell parts, which are usually where the bugs arise.

In fact, this has made me realize that GHC 8.6 and 8.8 reify equality constraints differently. Consider the following program:

```haskell
{-# LANGUAGE NoMonomorphismRestriction #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}
module Main where

import Language.Haskell.TH

type family F a

f :: (F a ~ Bool) => a
f = f

g = f

$(pure [])

main :: IO ()
main = do
  putStrLn $(reify 'f >>= stringE . show)
  putStrLn $(reify 'g >>= stringE . show)
```

In GHC 8.6.3, this produces the following output:

```
VarI Main.f (ForallT [KindedTV a_6989586621679016156 StarT] [AppT (AppT (ConT Data.Type.Equality.~) (AppT (ConT Main.F) (VarT a_6989586621679016156))) (ConT GHC.Types.Bool)] (VarT a_6989586621679016156)) Nothing
VarI Main.g (ForallT [KindedTV a_6989586621679016502 StarT] [AppT (AppT EqualityT (AppT (ConT Main.F) (VarT a_6989586621679016502))) (ConT GHC.Types.Bool)] (VarT a_6989586621679016502)) Nothing
```

But in GHC 8.7, it produces:

```
VarI Main.f (ForallT [KindedTV a_6989586621679016219 StarT] [AppT (AppT (ConT GHC.Types.~) (AppT (ConT Main.F) (VarT a_6989586621679016219))) (ConT GHC.Types.Bool)] (VarT a_6989586621679016219)) Nothing
VarI Main.g (ForallT [KindedTV a_6989586621679016250 StarT] [AppT (AppT (ConT GHC.Types.~) (AppT (ConT Main.F) (VarT a_6989586621679016250))) (ConT GHC.Types.Bool)] (VarT a_6989586621679016250)) Nothing
```

Notice how in the type of `g`, we've switched from reifying `ConT ''(~)` to `EqualityT`! (This is the reason why `dependent-db` fails to compile with GHC 8.7.)

Whether this change in behavior is a good thing or not is debatable. What's especially weird is that `f`'s type is _always_ reified using `ConT ''(~)`—it's only when the type is inferred (as in `g`) that things become unpredictable.

**Comment by goldfirere** [comment] 2019-01-25 02:45
OK. You've convinced me that this is worth keeping up-to-date. But I really think TH should produce `EqualityT` for both `f` and `g`. If you agree, then let's move this conversation to a GHC bug.

**Comment by RyanGlScott** [comment] 2019-01-25 02:45
The culprit is [this part](https://gitlab.haskell.org/ghc/ghc/blob/886ddb27bfbbb52c41690cd29e2ab3ed80bf5450/compiler/typecheck/TcSplice.hs#L2010-2014) of `TcSplice.reify_tc_app`:

```haskell
         | tc `hasKey` heqTyConKey        = TH.EqualityT
         | tc `hasKey` eqPrimTyConKey     = TH.EqualityT
         | tc `hasKey` eqReprPrimTyConKey = TH.ConT (reifyName coercibleTyCon)
         | isPromotedDataCon tc           = TH.PromotedT (reifyName tc)
         | otherwise                      = TH.ConT (reifyName tc)
```

It appears that unboxed equality (and boxed heterogeneous equality) is reified using `EqualityT`, whereas boxed homogeneous equality is reified using `ConT ''(~)`. GHC 8.7's type inference seems to have changed (likely in [f265008fb6f70830e7e92ce563f6d83833cef071](https://gitlab.haskell.org/ghc/ghc/commit/f265008fb6f70830e7e92ce563f6d83833cef071)) so that `g`'s type is inferred to have a boxed equality constraint instead of an unboxed one.

**Comment by goldfirere** [comment] 2019-01-25 02:52
Well, that's just plain wrong. `EqualityT` gets converted to `eqTyCon`, which is homogeneous. So it looks like `~~` won't survive a round-trip. I say that `EqualityT` should uniquely refer to homogeneous equality. And I would hope that `reify_tc_app` doesn't see primitive equality, ever.

**Comment by RyanGlScott** [comment] 2019-01-25 03:00
> Well, that's just plain wrong. `EqualityT` gets converted to `eqTyCon`, which is homogeneous. So it looks like `~~` won't survive a round-trip. I say that `EqualityT` should uniquely refer to homogeneous equality.

Sounds reasonable.

> And I would hope that `reify_tc_app` doesn't see primitive equality, ever.

I don't think that's a safe assumption to make. You can reify the definitions of `(~)`/`(~~)`/`Coercible`, after all, and all of them have unboxed equalities as superclasses (at least, as of commit [f265008fb6f70830e7e92ce563f6d83833cef071](https://gitlab.haskell.org/ghc/ghc/commit/f265008fb6f70830e7e92ce563f6d83833cef071)).

**Comment by goldfirere** [comment] 2019-01-25 03:07
OK, fair enough. But then `reify_tc_app` should just pass those through without trying to pretty them up.
